# Generated by Django 3.1.6 on 2021-07-15 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default-img.png', upload_to='product_pics', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_author', models.CharField(max_length=30)),
                ('phone_contact', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('postal_code', models.CharField(max_length=25)),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=13)),
                ('main_img', models.ImageField(default='default-img.png', upload_to='product_pics', verbose_name='Image')),
                ('sell', models.BooleanField(choices=[(True, 'Sell'), (False, 'Want')], default=True)),
            ],
        ),
    ]
