# Generated by Django 3.1.6 on 2021-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='category',
            field=models.CharField(choices=[('inappropriate', 'It contains offensive and/or inappropriate language and/or content.'), ('spam', 'It is spam'), ('laws', "It doesn't conform to laws"), ('false_info', 'It contains false information'), ('irrelevant', 'It is irrelevant'), ('other', 'Other')], default='spam', max_length=70),
        ),
    ]
